package gemmini

import chisel3._
import chisel3.util._
import chiseltest._
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

/** Software mirror of AccumulatorMem.applyE9M0Scale.
 *  Operates on raw integer bit-patterns (not Chisel hardware).
 *
 *  @param valueBits  raw bits of the FP value (totalBits = 1+expBits+mantBits)
 *  @param scaleE9M0  combined E9M0 scale code (9-bit unsigned, bias=254)
 *  @param expBits    number of exponent bits in valueBits
 *  @param mantBits   number of mantissa bits in valueBits
 *  @return           scaled raw bits with clamped exponent
 */
object ApplyE9M0Scale {
  def apply(valueBits: Int, scaleE9M0: Int, expBits: Int, mantBits: Int): Int = {
    val totalBits = 1 + expBits + mantBits
    val mask      = (1 << totalBits) - 1
    val v         = valueBits & mask

    val sign    = (v >> (totalBits - 1)) & 1
    val expMask = (1 << expBits) - 1
    val exp     = (v >> mantBits) & expMask
    val mant    = v & ((1 << mantBits) - 1)

    val scaleOffset = scaleE9M0 - 254
    val newExp      = exp + scaleOffset
    val maxExp      = expMask

    val clampedExp  = math.max(0, math.min(maxExp, newExp))
    val isZero      = (exp == 0) && (mant == 0)
    val finalExp    = if (isZero) 0 else clampedExp

    (sign << (expBits + mantBits)) | (finalExp << mantBits) | mant
  }
}

/** FP6 E3M2 decode helper (1 sign | 3 exp | 2 mantissa, bias=3). */
object Fp6E3M2 {
  val BIAS   = 3
  val E_BITS = 3
  val M_BITS = 2

  def decode(raw: Int): scala.Float = {
    val sign = (raw >> (E_BITS + M_BITS)) & 1
    val e    = (raw >> M_BITS) & 0x7
    val m    =  raw            & 0x3
    val mag: scala.Float =
      if (e == 0) {
        if (m == 0) 0.0f
        else (m.toFloat / 4.0f) * math.pow(2.0, 1 - BIAS).toFloat
      } else {
        (1.0f + m.toFloat / 4.0f) * math.pow(2.0, e - BIAS).toFloat
      }
    if (sign == 1) -mag else mag
  }
}

/**
 * MxPEMulFp6MatmulSpec
 *
 * Drives MxFpMulHarnessBf16Out_NewIO with A_mapped[32][16] and
 * B_mapped[16][32] FP6 E3M2 data matching lut_mapping_demo.py
 * (seed=0, fp6:e3m2, LUT_INDEX_BITS=4).
 *
 * Loop structure:
 *   outer : k = 0 .. 15
 *   inner : i = 0,2,..,30  (2-row tile)
 *           j = 0,2,..,30  (2-col tile)
 *
 * Per-cycle stimulus:
 *   in_activation : pack( A[i][k], A[i+1][k] ) → bits[5:0] / bits[11:6]
 *   in_weights    : pack( B[k][j], B[k][j+1] ) → bits[5:0] / bits[11:6]
 *
 * Lane outputs (FP6 × FP6, 2 acts × 2 weights):
 *   lane0 = A[i][k]   * B[k][j]   → C[i  ][j  ]
 *   lane1 = A[i][k]   * B[k][j+1] → C[i  ][j+1]
 *   lane2 = A[i+1][k] * B[k][j]   → C[i+1][j  ]
 *   lane3 = A[i+1][k] * B[k][j+1] → C[i+1][j+1]
 */
class MxPEMulFp6MatmulSpec
    extends AnyFlatSpec
    with ChiselScalatestTester
    with Matchers {

  import Fp6E3M2._

  behavior of "MxFpMul — FP6 E3M2; A[32][16] × B[16][32] from lut_mapping_demo.py"

  // -------------------------------------------------------------------------
  // A_mapped[32][16] — FP6 E3M2 raw 6-bit codes, generated by lut_mapping_demo.py
  // (seed=0, fp6:e3m2, LUT_INDEX_BITS=4)
  // -------------------------------------------------------------------------
  val A_mapped: Array[Array[Int]] = Array(
    Array(45,41,41,13,43,12,40,37, 0, 9, 0, 9, 7, 0,45,40),
    Array(45, 0,11,45,39,44, 9,13,43,10, 0,13,10,12, 0,39),
    Array(37,40,12, 7,43, 7, 7, 0,40,37, 7,12,13,44,13,37),
    Array(39, 7,13, 7, 9, 0, 7, 7,37,41,13,13,11,13,44,46),
    Array(11, 7,46,49, 9,12, 0, 0, 9, 0,13, 0, 9,37,13, 0),
    Array(10, 0,13,46, 7,40,11, 9,45,44,12,13,46,37,41,13),
    Array(37, 9,40,37,13,10,37,37, 0, 0,12, 7, 7,10,40,13),
    Array(49, 7, 7, 7,44, 9,12,45,37,40,39,13,10,41,13,46),
    Array( 7, 0,46, 7, 0, 7, 0, 0, 0,43,45,11,13,44,37, 0),
    Array(45,10,40, 0, 0, 0,44,40,13,11,13, 0,13, 7,37, 9),
    Array( 7,37,40, 7,41, 0, 7,40, 9,41, 7,10,12, 9,13, 7),
    Array( 7, 0,40, 7,45, 7, 9,11,40,13, 7,44,46,13,13,41),
    Array( 0, 7,44, 7, 0,37, 9,43,37,13, 0,43,41,13, 0,44),
    Array(13,13,12,43,44,44,45,11,45,41,49,37, 9,41,13,13),
    Array(12,46, 0,10,37, 7, 9,13,13,12,13,37,13,12,39,43),
    Array(37,46,10,43, 7,46,40,46,13,39,45, 7,41,46,13, 9),
    Array(45,41, 0,37,37, 0,13,46,37,41, 9, 7,43,13, 7, 7),
    Array(46,11, 9,49, 0,37, 0,46,10,37,13,11, 7,13,46, 0),
    Array( 9,12,43, 0, 7,46,12, 0, 9,40, 0, 7, 0,40,41,45),
    Array(10, 0, 0, 0,13,37,11,44, 7,10, 7,13,49, 7, 9,41),
    Array( 9,37,11,12, 7,12,45,13,49, 0, 7, 7,13,13, 7,37),
    Array(46,39,39, 7, 7, 0,12, 0, 9,44,40,40,40, 7, 0,44),
    Array(37, 9,12,43,37,13,40, 9,40, 0,44, 0,13,40, 7,44),
    Array(13,39, 7, 0, 0,10,45,37,43,44,13, 9,44,37,37, 9),
    Array(10,39,37,41, 0,44,12, 0, 0,45,13,37,13, 7,46,37),
    Array(41,10,13,39,43,41,13,12,13, 7,45,40,45, 0, 9,10),
    Array(37,13,46,13,46,13,41,11, 7,45,49,40,10, 7,45,49),
    Array( 0,13, 0,39, 0, 7, 9,40,37,45,49,45,13,43, 0,49),
    Array(13,46,44, 0,41, 9, 7,43,45,13,11,37,41, 7, 0, 7),
    Array(13,45,44,13, 7,44, 0, 0,37, 0,41, 9, 0,37,43,46),
    Array(12,13, 0,11, 0,45,44,13,12,39,13,37,13,13,13,13),
    Array(43,40,10,13, 7,45, 0, 7,45,37,44,37,13,37,49,46)
  )

  // -------------------------------------------------------------------------
  // B_mapped[16][32] — FP6 E3M2 raw 6-bit codes, generated by lut_mapping_demo.py
  // -------------------------------------------------------------------------
  val B_mapped: Array[Array[Int]] = Array(
    Array(45, 0,41,45, 9,46,15, 8, 8, 0, 0,43, 9,14,11,45, 9,11,42, 0, 9,11,15,46, 0,48, 8, 9,46,43, 9, 8),
    Array(41, 9,48,11,37,14,45,48,15,14,11, 0,41,47,45,11,41, 8,45, 0, 0, 9,39,45,46, 8,48, 0,37,42,48, 8),
    Array(45, 9,43,47,42,46, 9, 9, 0, 0, 0, 9, 0,11,39,42,37,42, 8, 8,45,11, 9, 0, 8,46, 0, 0,41,11, 8, 0),
    Array(38, 0, 8, 8,37,11,39, 0,43, 0, 8,45, 0,37, 8, 9, 0,11,46, 0, 0,14, 8, 9,45, 0,46, 0,45, 9,41, 0),
    Array( 8,41, 0, 8,37,14,43,46, 0,11,15,37,42,15,39, 0,41,42,41, 9,39,37,11,14,41, 0, 9,15, 8, 8,39, 0),
    Array( 0, 8,43,11,11,37, 0,45,41,37, 0,15,48, 8,45,14,46,14,39, 0,37,11, 9,15, 8,15,15, 8,41, 8, 0, 0),
    Array(46, 0, 8, 0, 8, 8,11,14, 8,47, 8,46,48,14,41, 0, 9, 0,42, 8, 8,14,11, 0, 8,43,46, 0,14, 8,14, 8),
    Array(15,11, 9,15,14,37,14,11,46, 0,47,46, 8, 0,42,11,14, 0,45,48,15,37, 8,14, 8,14,11,15,39,48,43,48),
    Array(38, 9, 9, 9,43,41, 9,15, 8,11,45,45,14, 8, 9,11,11, 0,37, 8,11,45,15,47,45,42,15, 8, 8,37,37,14),
    Array(45,39,45,11, 0, 8,48,41, 0,37, 9,14, 0,39, 9,14, 0,37,41,37,11,45,42,11,43, 9,41,37,15,45, 0,38),
    Array(11,11,48, 8,37,45,37,48,37,37, 9, 0,14,15,42,47,14,15, 0, 9,14,46,47,42,11,46, 9,46, 0,11, 0,39),
    Array(11,14,45,41,11, 8,45,11,39,41, 0,14,15,39, 0,37,47,14,15,37,45,42,11,37,39,15, 9,41,43,37,46,11),
    Array( 8, 9, 8,43,48,15,39, 0,46, 0,14,39, 0,14,15,14, 0,38, 8, 0,42, 8, 8,14, 0,14,15,14, 0, 0, 0, 0),
    Array(42,11, 9, 8, 8,42, 0,11, 0, 0,42,37,43,14,43, 0,43,11, 0, 0,11,41,43,37, 8, 8,43,46,37,11, 0, 0),
    Array(15,15,42, 0, 8, 9,39, 0,39,47, 0, 8, 0,39,48,14,47,11,15,46,14, 8,37,41,14, 8,39, 0,43, 0,41,15),
    Array( 0,11,39,15,43,48,45, 0,11, 8, 9, 8, 8, 0, 8,11,47,42,11,42,15,48,37, 8, 8,14,39, 8,43, 0, 0,11)
  )
   // ---- Print A_mapped and B_mapped in hex ----
        println("\n=== A_mapped[32][16] in hex ===")
        for (i <- 0 until 32) {
          val cells = A_mapped(i).map(v => f"0x${v}%02X").mkString(" ")
          println(f"  A[$i%02d]: $cells")
        }
        println("\n=== B_mapped[16][32] in hex ===")
        for (k <- 0 until 16) {
          val cells = B_mapped(k).map(v => f"0x${v}%02X").mkString(" ")
          println(f"  B[$k%02d]: $cells")
        }

  // -------------------------------------------------------------------------
  // A_scales_row[32] and B_scales_col[32] — fpe8m0 codes from matmul_data_mx_fp6.h
  // -------------------------------------------------------------------------
  val A_scales_row: Array[Int] = Array(
    0x83, 0x82, 0x83, 0x7f, 0x81, 0x7f, 0x83, 0x7e, 0x80, 0x7f, 0x80, 0x7e, 0x83, 0x7e, 0x7d, 0x7e,
    0x83, 0x84, 0x7e, 0x7d, 0x83, 0x7d, 0x84, 0x7e, 0x80, 0x83, 0x82, 0x81, 0x7d, 0x7d, 0x81, 0x7e
  )
  val B_scales_col: Array[Int] = Array(
    0x82, 0x7e, 0x7d, 0x7f, 0x82, 0x7d, 0x7f, 0x82, 0x7b, 0x80, 0x7b, 0x82, 0x7c, 0x7e, 0x7f, 0x7f,
    0x7f, 0x81, 0x7c, 0x80, 0x81, 0x81, 0x7e, 0x7d, 0x7c, 0x7f, 0x7b, 0x7e, 0x7d, 0x80, 0x7b, 0x7e
  )

  // -------------------------------------------------------------------------
  it should "tile A[32][16] × B[16][32] through the PE and compare against SW" in {

    val fpProductPrecision = (8, 8)
    val fpAccPrecision     = gemmini.MxFloat(8, 8, 4, true, false)

    test(new MxFpMulHarnessBf16Out_NewIO(lut = false, fpProductPrecision, fpAccPrecision))
      .withAnnotations(Seq(WriteVcdAnnotation)) { h =>

        def bf16ToFloat(raw16: Int): scala.Float =
          java.lang.Float.intBitsToFloat(raw16 << 16)

        def laneVal(bits: BigInt, idx: Int): Int =
          ((bits >> (idx * 16)) & 0xFFFFL).toInt

        val aW = h.io.in_activation.getWidth   // 12
        val wW = h.io.in_weights.getWidth       // 12

        // Pack two 6-bit FP6 elements: elem0 → bits[5:0], elem1 → bits[11:6]
        def pack2(r0: Int, r1: Int): BigInt =
          BigInt(r0 & 0x3F) | (BigInt(r1 & 0x3F) << 6)

        // ---- SW golden reference ----
        val swC = Array.ofDim[scala.Float](32, 32)
        for (i <- 0 until 16; j <- 0 until 16)
          for (k <- 0 until 16) {
            val a0 = decode(A_mapped(2*k)(i))
            val a1 = decode(A_mapped(2*k+1)(i))
            val w0 = decode(B_mapped(k)(2*j))
            val w1 = decode(B_mapped(k)(2*j+1))
            val prod_0 = a0 * w0
            val prod_1 = a0 * w1
            val prod_2 = a1 * w0
            val prod_3 = a1 * w1
            swC(2*i  )(2*j  ) += prod_0
            swC(2*i  )(2*j+1) += prod_1
            swC(2*i+1)(2*j  ) += prod_2
            swC(2*i+1)(2*j+1) += prod_3
          }

        // ---- HW accumulation array ---  -
        val hwC = Array.ofDim[scala.Float](32, 32)
        
       
        val C_scale = Array.tabulate(32, 32)((m, n) => A_scales_row(m) + B_scales_col(n))
        println("\n=== C_scale[32][32] outer product (fpe9m0) ===")
        for (m <- 0 until 32) {
          val cells = C_scale(m).map(v => f"0x${v}%03X").mkString(" ")
          println(f"  C_scale[$m%02d]: $cells")
        }

        // ---- Configure PE for FP6 E3M2 (altfmt=1 → exp=3, sig=3) ----
        h.io.type_a.exp.poke(3.U)
        h.io.type_a.sig.poke(3.U)
        h.io.type_w.exp.poke(3.U)
        h.io.type_w.sig.poke(3.U)
        h.io.enable.poke(true.B)
        h.io.c_raw.poke(0x0000.U(16.W))   // c = 0.0, accumulate in SW

        // ---- Outer: k = 0..15; Inner: i step 2, j step 2 ----
       
        for (i <- 0 until 4) {
          for (j <- 0 until 4) {
            for (k <- 0 until 16) {  
              val a0 = A_mapped(2*k)(i)
              val a1 = A_mapped(2*k+1)(i)
              val w0 = B_mapped(k)(2*j  )
              val w1 = B_mapped(k)(2*j+1)
             
              h.io.in_activation.poke(pack2(a0, a1).U(aW.W))
              h.io.in_weights   .poke(pack2(w0, w1).U(wW.W))
              
              h.clock.step(2)   // latency cushion

              val out = h.io.out_bf16.peek().litValue
              hwC(2*i  )(2*j  ) += bf16ToFloat(laneVal(out, 0))  // A[i][k]   * B[k][j]
              hwC(2*i  )(2*j+1) += bf16ToFloat(laneVal(out, 1))  // A[i][k]   * B[k][j+1]
              hwC(2*i+1)(2*j  ) += bf16ToFloat(laneVal(out, 2))  // A[i+1][k] * B[k][j]
              hwC(2*i+1)(2*j+1) += bf16ToFloat(laneVal(out, 3))  // A[i+1][k] * B[k][j+1]
              if(j==0 && i==0) {
              println(f"\nCycle: k=$k, i=$i, j=$j | A[i][k]=0x${a0}%02X, A[i+1][k]=0x${a1}%02X, B[k][j]=0x${w0}%02X, B[k][j+1]=0x${w1}%02X")
              println(f"\n Poked in_activation = 0x${pack2(a0, a1)}%03X, in_weights = 0x${pack2(w0, w1)}%03X")
              println(f"\n scale_a[0]=0x${A_scales_row(0)}%02X scale_a[1]=0x${A_scales_row(1)}%02X | scale_b[0]=0x${B_scales_col(0)}%02X scale_b[1]=0x${B_scales_col(1)}%02X")
              println(f" scale_c[0][0]=0x${C_scale(0)(0)}%03X, scale_c[0][1]=0x${C_scale(0)(1)}%03X, scale_c[1][0]=0x${C_scale(1)(0)}%03X, scale_c[1][1]=0x${C_scale(1)(1)}%03X")
              println(f" HW out hwC[0][0]=${hwC(0)(0)}%.4f(0x${floatToBf16Raw(hwC(0)(0))}%04X) hwC[0][1]=${hwC(0)(1)}%.4f(0x${floatToBf16Raw(hwC(0)(1))}%04X) hwC[1][0]=${hwC(1)(0)}%.4f(0x${floatToBf16Raw(hwC(1)(0))}%04X) hwC[1][1]=${hwC(1)(1)}%.4f(0x${floatToBf16Raw(hwC(1)(1))}%04X)")    
              //println(f" SW out swC[0][0] = ${swC(0)(0)}, swC[0][1] = ${swC(0)(1)}, swC[1][0] = ${swC(1)(0)}, swC[1][1] = ${swC(1)(1)}")
              }
            }
          }
        }

        def floatToBf16Raw(f: scala.Float): Int = {
          val bits = java.lang.Float.floatToRawIntBits(f)
          val lsb  = (bits >>> 16) & 1
          val rnd  = bits + (0x7FFF + lsb)
          (rnd >>> 16) & 0xFFFF
        }

        // ---- C_scale[32][32] outer product in fpe9m0 ----
        // fpe8m0 (bias=127): val = 2^(code-127)
        // fpe9m0 (bias=255): val = 2^(code-255)
        // A_scale * B_scale = 2^((a-127)+(b-127)) => fpe9m0 code = a + b + 1
        

        // ---- Method 1 (original): multiply by 2^(scaleExp) in float ----
        val scaled_hwC_orig = Array.tabulate(32, 32) { (m, n) =>
          val scaleExp = C_scale(m)(n) - 254
          hwC(m)(n) * math.pow(2.0, scaleExp).toFloat
        }

        // ---- Method 2: ApplyE9M0Scale (mirrors AccumulatorMem hardware, operates on raw BF16 bits) ----
        val scaled_hwC = Array.tabulate(32, 32) { (m, n) =>
          val rawBf16   = floatToBf16Raw(hwC(m)(n))
          val scaledRaw = ApplyE9M0Scale(rawBf16, C_scale(m)(n), expBits = 8, mantBits = 7)
          bf16ToFloat(scaledRaw)
        }

        // ---- Print first 4×4 corner: compare both methods ----
        println("\n=== C = A[32][16] × B[16][32], FP6 E3M2 — first 4×4 corner ===")
        println("            HW float    HW hex  | orig scaled   orig hex  | hw scaled    hw hex")
        for (i <- 0 until 4; j <- 0 until 4) {
          val hwHex      = f"0x${floatToBf16Raw(hwC(i)(j))}%04X"
          val origHex    = f"0x${floatToBf16Raw(scaled_hwC_orig(i)(j))}%04X"
          val scaledHex  = f"0x${floatToBf16Raw(scaled_hwC(i)(j))}%04X"
          println(f"  C[$i%02d][$j%02d]  ${hwC(i)(j)}%10.4f  $hwHex%8s  | ${scaled_hwC_orig(i)(j)}%12.4f  $origHex%8s  | ${scaled_hwC(i)(j)}%12.4f  $scaledHex%8s")
        }
      
        // // ---- Print A_mapped rows 0..3 ----
        // println("\n=== A_mapped[0..3][0..15] (hex | float) ===")``
        // for (i <- 0 until 4) {
        //   val cells = A_mapped(i).zipWithIndex
        //     .map { case (v, k) => val fv: scala.Float = decode(v); f"[k$k%02d]0x${v}%02X($fv%.2f)" }.mkString(" ")
        //   println(s"  A[$i]: $cells")
        // }

        // // ---- Print B_mapped rows 0..15, cols 0..3 ----
        // println("\n=== B_mapped[0..15][0..3] (hex | float) ===")
        // for (k <- 0 until 16) {
        //   val cells = (0 until 4)
        //     .map { j => val v = B_mapped(k)(j); val fv: scala.Float = decode(v); f"[j$j%02d]0x${v}%02X($fv%.2f)" }.mkString(" ")
        //   println(s"  B[$k]: $cells")
        // }

        h.io.enable.poke(false.B)
        h.clock.step(1)
      }
  }
}
